### ISSUE TITLE
[Epic] New Version

### ISSUE THREAD

**Issue by greyscaled** [greyscaled/Validate#58]
- [ ] Replace Travis with GH Actions
- [ ] Change NPM package location
- [ ] Re-Host documentation
- [ ] Update development environment and toolchain
